version: '3.8'

services:
  postgres_db:
    container_name: postgres
    image: postgres:alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_USER=${USER}
      - POSTGRES_DB=google_keep
      - POSTGRES_COLLATION=en_US.utf8
      - POSTGRES_CTYPE=en_US.utf8
    healthcheck:
      test: ["CMD", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 1
    ports:
      - 5432:5432
  app:
    container_name: GoogleKeep
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - postgres_db
  angular:
    container_name: angular
    build:
      context: ./GoogleKeep
      dockerfile: ./GoogleKeep/Dockerfile.angular

volumes:
  postgres_data:
