version: '3.8'

services:
  postgres_db:
    container_name: postgres
    image: postgres:alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_USER=${USER}
      - POSTGRES_DB=${NAME}
      - POSTGRES_COLLATION=en_US.utf8
      - POSTGRES_CTYPE=en_US.utf8
    healthcheck:
      test: ["CMD", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 1
    ports:
      - 5432:5432
  app:
    container_name: Keep
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn google_keep.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    restart: always
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - postgres_db
  dj-nginx:
    container_name: dj-nginx
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - app

volumes:
  postgres_data:
  static_volume:
  media_volume:
