# Generated by Django 4.1.7 on 2023-02-18 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=255, null=True)),
                ('remainder', models.DateTimeField(null=True)),
                ('is_archive', models.BooleanField(default=False)),
                ('is_trash', models.BooleanField(default=False)),
                ('collaborator', models.ManyToManyField(related_name='collaborator', to=settings.AUTH_USER_MODEL)),
                ('label', models.ManyToManyField(related_name='label', to='labels.label')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'note',
            },
        ),
    ]
