# Generated by Django 4.1.7 on 2023-11-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_archive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_trash',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
